### ISSUE TITLE
useRequest好像有点问题

### ISSUE THREAD

**Issue by Tony-stark-ui** [itmanyong/uni-vite-vue3-project-basis-template#1]
js函数中有异步操作return会优先执行，外面调用的时候获取到的数据是null，等接口返回了再赋值在外面依然取不到，控制台可以打印出data，但是拿不到里面的数据

**Comment by itmanyong** [comment]
因为是异步获取的原因,所以返回真实数据的时间不确定，拿到为null是正常的。
经测试返回数据后外面是可以拿到的，无论是模板还是逻辑中，如下：
![image](https://user-images.githubusercontent.com/53500371/200623189-cbfd824c-2f50-42a4-8ff6-45dd29ced630.png)
